var s="";
s+="<div id='footer'><table cellpadding='0' cellspacing='0'><tr>";
s+="<td>网址：www.qijiuhealthcare.com";
s+="<br>粤ICP备16067818号<br>";
//s+="粤卫网审（2016）###号";
s+="&nbsp;</td><td>地址：广州市白云区龙归攀龙创意园4楼401-411";
s+="<br>电话：（020）36796590<br>";
s+="广州柒玖医疗发展有限公司　版权所有";
//s+="传真：（020）########";
s+="</td><td>微信公众号：柒玖医疗";
s+="<br>电邮：qijiuhealthcare@hotmail.com<br>";
s+="&nbsp;</td></tr></table></div>";
document.write(s);
